name: CI

on:
  pull_request:
  push:
    branches-ignore: [master, release] # Don't run this double on merge

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Save money/time by cancelling outdated runs

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@v4 # Note: v4 is the current standard
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn' # AUTOMATICALLY caches node_modules

      - run: yarn install --immutable

      - name: Initialise database
        run: yarn initdb
        env:
          DYNAMODB_ENDPOINT: http://localhost:8000

      - name: Run Tests
        run: yarn test run

      - name: Run Lint
        run: yarn lint
